# Generated by Django 2.0.5 on 2018-09-03 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeend',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
