# Generated by Django 2.0.5 on 2018-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('southafrica', 'SOUTHAFRICA'), ('america', 'AMERICA'), ('england', 'ENGLAND'), ('russia', 'RUSSIA'), ('china', 'CHINA')], default='america', max_length=30),
        ),
    ]
