# Generated by Django 2.0.5 on 2018-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_post_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='imgs/None/no-img.jpg', height_field='200', upload_to='imgs/', width_field='200'),
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('southafrica', 'South Africa'), ('america', 'America'), ('england', 'England'), ('russia', 'Russia'), ('china', 'China')], default='america', max_length=30),
        ),
    ]
