# Generated by Django 2.0.5 on 2018-09-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_auto_20180918_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none/none.png', upload_to='imgs'),
        ),
    ]
