# Generated by Django 2.0.5 on 2018-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_auto_20180924_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='no location specified', max_length=30),
        ),
    ]
