# Generated by Django 2.0.5 on 2018-10-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(default='no keywords', max_length=30),
        ),
    ]
